# features/find_asset.feature
@provision
@finder
@find_provision
@find_countries
@countries_finder

Feature: Find a countries
    As a user of JsApi
    I want to find a countries
    So I can check if a countries exists and get their information

    Background:
        Given an apikey user by "require-real-apikey" and...
            | key                 | value                                                                                          |
            | _internalCountriesFilter | {"resourceType": "entity.asset","specificType": "WIRE", "identifier": "DOMAIN_country_organization5"} |

    Scenario: Precondition - Creating an organization to use in create asset
        Given an ogapi "organizations builder" util
        Then I want to create an "organization"
        And the "name" "country_organization"
        And the "description" "country_organization"
        And the "country code" "ES"
        And the "lang code" "es"
        And the "time zone" "Europe/Andorra"
        And the "zoom" 10
        And the "location" with 1 and 1
        Then I delete it
        And I create it
        And response code should be: 201

    Scenario: Precondition - Create a datamodel
        Given an ogapi "datamodels builder" util with...
            | param                |
            | country_organization |
        And I want to create a "datamodel"
        And the "identifier" "country"
        And the "name" "country"
        And the "version" "1.0"
        And the "description" "TESTING"
        And the "allowed resource type" "entity.asset"
        And the
            | method      | value                                           |
            | addCategory | {"name":"countries", "identifier": "countries"} |
        And the "add datastream" with...
            | param                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
            | countries                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |
            | {"identifier": "provision.onfieldDeployments.fa.location","name": "provision.onfieldDeployments.fa.location","description": "for tests","period": "PULSE","tags": ["test","countries"], "schema" : {"type": "array","items": {"type": "object","properties": {"name": {"type": "string"},"regions": {"type": "array","items": {"type": "object","properties": {"name": {"type": "string"},"provinces": {"type": "array","items": {"type": "object","properties": {"name": {"type": "string"},"postalCodes": {"type": "array","items": {"type": "string"}}}}}}}}}}}, "access": "READ" } |
        Then I create it
        And response code should be: 201

    Scenario: Precondition - I want to create an asset
        Given the entity of type "asset builder" with "country_organization"
        And I get allowed Datastreams fields
        And I can found "provision.asset.identifier" as datastream name
        When I try to define the entity with...
            | datastream                               | typeFunction | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               | parent |
            | provision.administration.channel         | simple       | default_channel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |        |
            | provision.administration.organization    | simple       | country_organization                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |        |
            | provision.administration.serviceGroup    | simple       | emptyServiceGroup                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |        |
            | provision.asset.identifier               | simple       | DOMAIN_country_organization5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |        |
            | provision.administration.identifier               | simple       | DOMAIN_country_organization5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |        |
            | provision.asset.specificType               | simple       | WIRE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |        |
            | provision.onfieldDeployments.fa.location | simple json      | [{ "regions": [ { "provinces": [ { "postalCodes": [  ], "name": "Álava" }, { "postalCodes": [  ], "name": "Guipuzcua" }, { "postalCodes": [  ], "name": "Huesca" }, { "postalCodes": [  ], "name": "La Rioja" }, { "postalCodes": [  ], "name": "Navarra" }, { "postalCodes": [  ], "name": "Soria" }, { "postalCodes": [  ], "name": "Teruel" }, { "postalCodes": [  ], "name": "Vizcaya" }, { "postalCodes": [  ], "name": "Zaragoza" } ], "name": "Aragon" }, { "provinces": [ { "postalCodes": [  ], "name": "Islas Baleares" } ], "name": "Balearics" }, { "provinces": [ { "postalCodes": [  ], "name": "Las Palma" }, { "postalCodes": [  ], "name": "Sta. Cruz de Tenerife" } ], "name": "Canary islands" }, { "provinces": [ { "postalCodes": [  ], "name": "Barcelona" }, { "postalCodes": [  ], "name": "Girona" }, { "postalCodes": [  ], "name": "Lleida" }, { "postalCodes": [  ], "name": "Tarragona" } ], "name": "Catalonia" }, { "provinces": [ { "postalCodes": [  ], "name": "Albacete" }, { "postalCodes": [  ], "name": "Alicante" }, { "postalCodes": [  ], "name": "Ávila" }, { "postalCodes": [  ], "name": "Castellón" }, { "postalCodes": [  ], "name": "Cuenca" }, { "postalCodes": [  ], "name": "Guadalajara" }, { "postalCodes": [  ], "name": "Madrid" }, { "postalCodes": [  ], "name": "Salamanca" }, { "postalCodes": [  ], "name": "Segovia" }, { "postalCodes": [  ], "name": "Toledo" }, { "postalCodes": [  ], "name": "Valencia" } ], "name": "Center zone" }, { "provinces": [ { "postalCodes": [  ], "name": "Burgos" }, { "postalCodes": [  ], "name": "A Coruña" }, { "postalCodes": [  ], "name": "León" }, { "postalCodes": [  ], "name": "Lugo" }, { "postalCodes": [  ], "name": "Asturias" }, { "postalCodes": [  ], "name": "Palencia" }, { "postalCodes": [  ], "name": "Pontevedra" }, { "postalCodes": [  ], "name": "Cantabria" }, { "postalCodes": [  ], "name": "Valladolid" }, { "postalCodes": [  ], "name": "Zamora" } ], "name": "North west zone" }, { "provinces": [ { "postalCodes": [  ], "name": "Almería" }, { "postalCodes": [  ], "name": "Badajoz" }, { "postalCodes": [  ], "name": "Cáceres" }, { "postalCodes": [  ], "name": "Cádiz" }, { "postalCodes": [  ], "name": "Ciudad Real" }, { "postalCodes": [  ], "name": "Córdoba" }, { "postalCodes": [  ], "name": "Granada" }, { "postalCodes": [  ], "name": "Huelva" }, { "postalCodes": [  ], "name": "Jaén" }, { "postalCodes": [  ], "name": "Málaga" }, { "postalCodes": [  ], "name": "Murcia" }, { "postalCodes": [  ], "name": "Sevilla" }, { "postalCodes": [  ], "name": "Ceuta" }, { "postalCodes": [  ], "name": "Melilla" } ], "name": "South zone" } ], "name": "Spain"} ] |        |
        Then I create it
        And response code should be: 201


    Scenario: Find a country
        Given an ogapi "countries finder" util
        And I want to read a "countries"
        When I try to find by...
			| field | content                |
			| countries ||
        And response code should be: 200
        Then I can see into the result an "country" as "Spain"
        Then I can see into the result an "region" as "Aragon"
        Then I can see into the result an "province" as "Álava"

    Scenario: I want to delete the entity
        Given the entity of type "asset builder" with "country_organization"
        When I try to define the entity with...
            | datastream                 | typeFunction | value                     | parent |
            | provision.asset.identifier | simple       | DOMAIN_country_organization5 |        |
        Then I delete it

    Scenario: Deleting an organization to use in create asset
        Given an ogapi "organizations builder" util
        Then I want to delete an "organization"
        And the "name" "country_organization"
        Then I delete it
